'use client'
import {useEffect,useMemo,useState} from 'react'
import {useParams} from 'next/navigation'
import {supabase} from '../../../lib/supabase'
type Item={id:string;name:string;price:number;unit:string;station:string;image_url?:string|null};type Cat={id:string;name:string;items:Item[]}
export default function TableOrder(){const {token}=useParams<{token:string}>();const [data,setData]=useState<any>(),[cart,setCart]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('');
 useEffect(()=>{supabase.rpc('get_table_menu',{p_qr_token:token}).then(({data,error})=>error?setData({error:error.message}):setData(data))},[token]);const items:Item[]=useMemo(()=>data?.categories?.flatMap((c:Cat)=>c.items||[])||[],[data]);const total=items.reduce((s,i)=>s+(cart[i.id]||0)*Number(i.price),0);const add=(id:string,n:number)=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+n)}));
 async function submit(){const lines=Object.entries(cart).filter(([,q])=>q>0).map(([menu_item_id,quantity])=>({menu_item_id,quantity}));if(!lines.length)return;setBusy(true);setErr('');setMsg('');const {data:r,error}=await supabase.rpc('submit_table_order',{p_qr_token:token,p_idempotency_key:crypto.randomUUID(),p_items:lines});setBusy(false);if(error)setErr(error.message);else{setCart({});setMsg('ส่งออเดอร์ #'+r.order_no+' เข้าครัวแล้ว');window.scrollTo({top:0,left:0,behavior:'auto'});setTimeout(()=>setMsg(''),2500)}}
 if(!data)return <main className="order"><h2>กำลังเปิดเมนู…</h2></main>;if(data.error)return <main className="order"><h2>QR นี้ใช้งานไม่ได้</h2></main>;
 const imageMode=data.restaurant.menu_display_mode!=='text';return <main className={'order '+(imageMode?'imageMode':'textMode')}><header><b>{data.restaurant.name}</b><span>{data.table.name}</span></header><section className="orderHero"><h1>สั่งอะไรดี?</h1><p>เลือกอาหารแล้วกดส่งเข้าครัวได้เลย</p></section>{msg&&<p style={{margin:'12px 16px',padding:12,borderRadius:12,background:'#e9f8ee',fontWeight:800,textAlign:'center'}}>✓ {msg}</p>}{err&&<p className="errorbar">{err}</p>}{data.categories.map((c:Cat)=><section className="menuCat" key={c.id}><h2>{c.name}</h2>{c.items.map(i=><article className="menuItem" key={i.id}>{imageMode&&<div style={{width:84,height:70,borderRadius:12,overflow:'hidden',background:'#f1f1f1',flex:'0 0 84px'}}>{i.image_url?<img src={i.image_url} alt={i.name} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<div style={{height:'100%',display:'grid',placeItems:'center',fontSize:28}}>🍽️</div>}</div>}<div style={{flex:1}}><b>{i.name}</b><small>฿{Number(i.price).toFixed(0)} / {i.unit}</small></div><div className="qty"><button onClick={()=>add(i.id,-1)}>−</button><strong>{cart[i.id]||0}</strong><button onClick={()=>add(i.id,1)}>+</button></div></article>)}</section>)}{total>0&&<div className="cartbar"><div><small>รวม</small><b>฿{total.toFixed(0)}</b></div><button disabled={busy} onClick={submit}>{busy?'กำลังส่ง…':'ส่งเข้าครัว'}</button></div>}</main>}
