'use client'
import {useEffect,useState} from 'react'
import QRCode from 'qrcode'
import {supabase} from '../../lib/supabase'
const DEVICE='b4d081df-bf03-47b4-bafb-7fc7269bcfed'
function tlv(id:string,v:string){return id+String(v.length).padStart(2,'0')+v}function crc(s:string){let c=0xffff;for(let i=0;i<s.length;i++){c^=s.charCodeAt(i)<<8;for(let j=0;j<8;j++)c=(c&0x8000)?((c<<1)^0x1021)&0xffff:(c<<1)&0xffff}return c.toString(16).toUpperCase().padStart(4,'0')}function payload(id:string,amount:number){const raw=id.replace(/\D/g,'');const merchant=raw.length===13?tlv('02',raw):tlv('01','0066'+raw.replace(/^0/,''));let p=tlv('00','01')+tlv('01','12')+tlv('29',tlv('00','A000000677010111')+merchant)+tlv('53','764')+tlv('54',amount.toFixed(2))+tlv('58','TH')+'6304';return p+crc(p)}
export default function Cashier(){const [tables,setTables]=useState<any[]>([]),[token,setToken]=useState(''),[bill,setBill]=useState<any>(),[usage,setUsage]=useState<any>(),[qr,setQr]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function usageLoad(){const {data}=await supabase.rpc('get_device_daily_usage',{p_device_token:DEVICE});setUsage(data)}async function loadTables(){const {data,error}=await supabase.rpc('get_cashier_tables',{p_device_token:DEVICE});if(error){setErr(error.message);return}const a=Array.isArray(data)?data:[];setTables(a);usageLoad();if(a.length&&!token){setToken(a[0].qr_token);load(a[0].qr_token)}}async function load(t=token){if(!t)return;setErr('');setQr('');const {data,error}=await supabase.rpc('cashier_get_bill',{p_device_token:DEVICE,p_qr_token:t});if(error){setErr(error.message);return}setBill(data);usageLoad()}useEffect(()=>{loadTables();const x=setInterval(usageLoad,10000);return()=>clearInterval(x)},[]);async function checkBill(){const {error}=await supabase.rpc('request_bill_payment',{p_qr_token:token});if(error){setErr(error.message);return}const {data,error:e}=await supabase.rpc('get_table_payment',{p_qr_token:token});if(e){setErr(e.message);return}if(!data.promptpay_id){setErr('ยังไม่ได้ตั้ง PromptPay ของร้าน');await load();return}setBill((b:any)=>({...b,status:'payment_requested',total:data.amount}));setQr(await QRCode.toDataURL(payload(data.promptpay_id,Number(data.amount)),{width:360,margin:1}))}async function served(id:string){setBusy(true);const {error}=await supabase.rpc('cashier_mark_order_served',{p_device_token:DEVICE,p_order_id:id});setBusy(false);if(error)setErr(error.message);else load()}async function close(method:string){if(busy)return;setBusy(true);const {error}=await supabase.rpc('cashier_close_bill',{p_device_token:DEVICE,p_qr_token:token,p_method:method});setBusy(false);if(error){setErr(error.message);return}setQr('');await load()}
const orderGroups=(bill?.items||[]).reduce((a:any,i:any)=>{(a[i.order_id]??={id:i.order_id,no:i.order_no,status:i.order_status,served:!!i.served_at,items:[]}).items.push(i);return a},{})
return <main className="cashier"><header><div><b>💵 แคชเชียร์ • สั่งครับ</b><small>วันนี้ {usage?.used??'-'}/{usage?.limit??50} ออเดอร์ • เช็กเสิร์ฟ • ปิดบิล</small></div><button onClick={()=>load()}>↻ อัปเดต</button></header>{usage?.over_limit&&<p className="upgradebar">วันนี้เกิน {usage.limit} ออเดอร์แล้ว • ระบบยังใช้งานต่อได้ • กรุณาอัปเกรดแพลน</p>}<section className="cashierPick"><select value={token} onChange={e=>{setToken(e.target.value);load(e.target.value)}}>{tables.map(t=><option key={t.qr_token} value={t.qr_token}>{t.name}</option>)}</select></section>{err&&<p className="errorbar">{err}</p>}{bill?.has_bill?<section className="cashBill"><div className="billTop"><b>{bill.table}</b><strong>฿{Number(bill.total).toFixed(0)}</strong></div>{Object.values(orderGroups).map((o:any)=><div key={o.id} className="cashOrder"><div><b>ออเดอร์ #{o.no}</b> <small>{o.status==='completed'?(o.served?'✓ เสิร์ฟแล้ว':'พร้อมเสิร์ฟ'):'กำลังทำ'}</small></div>{o.items.map((i:any,n:number)=><div className="billLine" key={n}><span>{i.quantity}× {i.name}</span><b>฿{Number(i.line_total).toFixed(0)}</b></div>)}{o.status==='completed'&&!o.served&&<button disabled={busy} className="servedBtn" onClick={()=>served(o.id)}>เสิร์ฟแล้ว</button>}</div>)}{qr?<div className="cashQr"><h2>สแกนชำระ ฿{Number(bill.total).toFixed(2)}</h2><img src={qr} alt="PromptPay QR"/><p>QR นี้ผูกยอดตามบิลปัจจุบัน</p><button disabled={busy} className="cashCheck" onClick={()=>close('promptpay')}>รับเงินแล้ว • ปิดบิล</button></div>:<><button className="cashCheck" onClick={checkBill}>เช็กบิล • สร้าง QR ฿{Number(bill.total).toFixed(0)}</button><button disabled={busy} className="cashCheck cashBtn" onClick={()=>close('cash')}>รับเงินสดแล้ว • ปิดบิล</button></>}</section>:<section className="empty"><b>โต๊ะนี้ยังไม่มีบิล</b><p>ปิดบิลแล้ว โต๊ะพร้อมเปิดบิลใหม่อัตโนมัติ</p></section>}</main>}
